version: "3.0"
services:
  myd-php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: ${APP_NAME}_php
    ports:
      - "${EXTERNAL_PORT:-8020}:80"
    volumes: 
      - ./:/var/www/html
    depends_on:
      - database
    env_file:
      - .env
    networks:
      - myd3

  # apache:
  #   build: 
  #     context: .
  #     dockerfile: ./docker/apache/Dockerfile
  #   depends_on:
  #     - myd-php
  #     - database
  #   ports:
  #     - "${EXTERNAL_PORT:-8020}:80"
  #   volumes:
  #     - ./:/var/www/html
  #   networks:
  #   - myd3
  database:
    build:
      context: ./docker/db
      dockerfile: Dockerfile.mysql
    container_name: ${APP_NAME}_database
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    ports:
      - "3320:3306"
    networks:
      - myd3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "${PHPMYADMIN_PORT:-8021}:80"
    depends_on:
      - database
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_PORT: ${DB_PORT}
      PMA_USER: ${DB_USERNAME}
      PMA_PASSWORD: ${DB_PASSWORD}
    networks:
      - myd3

networks:
  myd3: